$folders = @(
    "00-product-context",
    "01-inputs",
    "01-inputs\prd",
    "01-inputs\figma",
    "01-inputs\api-specs",
    "01-inputs\backend-docs",
    "01-inputs\frontend-docs",
    "01-inputs\mobile-docs",
    "01-inputs\cms-docs",
    "01-inputs\firebase-events",
    "01-inputs\release-notes",

    "02-agent-registry",

    "03-prompts",
    "03-prompts\00-global",
    "03-prompts\01-management-team",
    "03-prompts\02-test-planning",
    "03-prompts\03-product-flow",
    "03-prompts\04-design-ui-visual",
    "03-prompts\05-web-mobile-notification",
    "03-prompts\06-backend-db-realtime",
    "03-prompts\07-security-performance",
    "03-prompts\08-automation-development-in-test",
    "03-prompts\09-operations-reporting",
    "03-prompts\reviewers",
    "03-prompts\templates",

    "04-workflows",
    "04-workflows\00-master-workflows",
    "04-workflows\01-product-analysis",
    "04-workflows\02-test-case-generation",
    "04-workflows\03-design-validation",
    "04-workflows\04-backend-validation",
    "04-workflows\05-mobile-validation",
    "04-workflows\06-automation-generation",
    "04-workflows\07-reporting",
    "04-workflows\08-jira-trello",
    "04-workflows\n8n",

    "05-outputs",
    "05-outputs\test-plans",
    "05-outputs\test-cases",
    "05-outputs\happy-path",
    "05-outputs\edge-cases",
    "05-outputs\negative-cases",
    "05-outputs\risk-analysis",
    "05-outputs\automation-candidates",
    "05-outputs\design-review",
    "05-outputs\api-review",
    "05-outputs\db-review",
    "05-outputs\mobile-review",
    "05-outputs\security-review",
    "05-outputs\performance-review",
    "05-outputs\jira-trello",
    "05-outputs\reports",

    "06-tests",
    "06-tests\web-playwright",
    "06-tests\mobile-appium",
    "06-tests\api",
    "06-tests\db",
    "06-tests\performance-jmeter",
    "06-tests\security",
    "06-tests\fixtures",

    "07-integrations",
    "07-integrations\jira",
    "07-integrations\trello",
    "07-integrations\github",
    "07-integrations\firebase",
    "07-integrations\cms",
    "07-integrations\slack",
    "07-integrations\email",

    "08-skills",
    "08-skills\ui-testing",
    "08-skills\api-testing",
    "08-skills\mobile-testing",
    "08-skills\db-validation",
    "08-skills\socket-testing",
    "08-skills\visual-testing",
    "08-skills\security-testing",
    "08-skills\performance-testing",
    "08-skills\test-case-design",
    "08-skills\reporting",

    "09-docs",
    "09-docs\architecture",
    "09-docs\agent-guidelines",
    "09-docs\workflow-guidelines",
    "09-docs\prompt-standards",
    "09-docs\output-standards",
    "09-docs\runbooks",

    "10-scripts",
    "10-scripts\setup",
    "10-scripts\local-run",
    "10-scripts\validation",
    "10-scripts\reporting",
    "10-scripts\cleanup",

    "11-dashboard",
    "11-dashboard\operator-dashboard",
    "11-dashboard\mockups"
)

foreach ($folder in $folders) {
    New-Item -ItemType Directory -Force -Path $folder | Out-Null
}

Write-Host "Repository folder structure has been created or verified successfully."